# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5BqQhyJLb4snxp_96sTCs7jzBWIZ8Ix
"""

# 📦 Install required packages
!pip install yfinance pandas lxml --quiet

# 📚 Import libraries
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
import time

# 🧠 Step 1: Scrape all S&P 500 tickers from Wikipedia
def get_sp500_tickers():
    url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
    tables = pd.read_html(url)
    tickers = tables[0]['Symbol'].tolist()
    # Fix known ticker issues (e.g., BRK.B → BRK-B for Yahoo Finance)
    return [t.replace('.', '-') for t in tickers]

tickers = get_sp500_tickers()
print(f"✅ Found {len(tickers)} tickers")

# 🧮 Step 2: Define function to calculate momentum
def calculate_momentum(ticker):
    try:
        # Download 1 year of hourly data (max for free tier)
        df = yf.download(ticker, period='1y', interval='1h', progress=False)
        df = df['Close'].dropna()
        if df.empty or len(df) < 24*5:  # need at least 1 week of data
            return None

        now = df.index[-1]
        def pct_change(period_hours):
            past_index = now - timedelta(hours=period_hours)
            past_data = df[df.index <= past_index]
            if not past_data.empty:
                return (df.iloc[-1] - past_data.iloc[-1]) / past_data.iloc[-1]
            return None

        return {
            'Ticker': ticker,
            '1H': pct_change(1),
            '1W': pct_change(24*7),
            '1M': pct_change(24*30),
            '1Y': pct_change(24*365)
        }
    except:
        return None

# 🛠 Step 3: Loop through tickers and compile momentum data
results = []
for i, ticker in enumerate(tickers):
    print(f"[{i+1}/{len(tickers)}] Fetching {ticker}...")
    m = calculate_momentum(ticker)
    if m:
        results.append(m)
    time.sleep(0.2)  # Prevent rate limits

# 🧾 Step 4: Save to CSV
df = pd.DataFrame(results).dropna()
df.sort_values('1W', ascending=False, inplace=True)
df.to_csv("weekly_momentum.csv", index=False)
print("✅ Saved weekly_momentum.csv with", len(df), "rows")

# 🔍 Preview top 10
df.head(10)